version = 1

[merge]
automerge_label = "ðŸš€ Status: ship it"
blacklist_title_regex = "^WIP.*"
blacklist_labels = ["ðŸ›‘ Status: blocked"]
method = "squash"
delete_branch_on_merge = true
block_on_reviews_requested = true
notify_on_conflict = true
optimistic_updates = true
