sudo: false
os: osx

addons:
  apt:
    update: true
    sources:
      - deadsnakes
    packages:
      - python3.6

language: node_js

node_js:
  - '10'

notifications:
  email: false

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  # Install transifex
  - curl https://bootstrap.pypa.io/get-pip.py | sudo -H python3.6
  - (pip -V && pip3 -V && pip3.6 -V) | uniq
  - python3.6 -m pip install --user transifex-client
  - export PATH="$HOME/.local/bin:$PATH"
  # Install yarn
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
  - export PATH=$HOME/.yarn/bin:$PATH

script:
  - set -e
  - yarn run jest --projects jest.*.config.js --maxWorkers=4 --reporters jest-silent-reporter
  - yarn build
  - yarn playground:build
  - yarn --cwd application-templates/starter build
  - set +e

after_success:
  - ./scripts/release_canary.sh
  - ./scripts/push_translations.sh
